declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_WEBAPP_URL?: string;
    NEXT_PUBLIC_MARKETING_URL?: string;

    NEXT_PRIVATE_DATABASE_URL: string;

    NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_MONTHLY_PRICE_ID: string;

    NEXT_PRIVATE_STRIPE_API_KEY: string;
    NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET: string;

    NEXT_PRIVATE_GOOGLE_CLIENT_ID: string;
    NEXT_PRIVATE_GOOGLE_CLIENT_SECRET: string;

    NEXT_PRIVATE_OIDC_WELL_KNOWN: string;
    NEXT_PRIVATE_OIDC_CLIENT_ID: string;
    NEXT_PRIVATE_OIDC_CLIENT_SECRET: string;

    NEXT_PRIVATE_UPLOAD_TRANSPORT: string;
    NEXT_PRIVATE_UPLOAD_ENDPOINT?: string;
    NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE?: string;
    NEXT_PRIVATE_UPLOAD_REGION?: string;
    NEXT_PRIVATE_UPLOAD_BUCKET?: string;
    NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID?: string;
    NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY?: string;
  }
}
